FROM node:14.4.0 as build

WORKDIR /app

#COPY frontend/compute-system/package.json /app
#COPY frontend/compute-system/package-lock.json /app

COPY frontend/compute-system /app/

RUN rm -rf node_modules package-lock.json && npm install

RUN npm run build


FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx","-g", "daemon off;"]
